# https://decapcms.org/docs/backends-overview/
backend:
  name: git-gateway # adds users without giving them direct write access to your GitHub or GitLab repository.
  branch: main # default: master
  cms_label_prefix: decap-cms # default: netlify-cms/
  # Options:
  # name: github/gitlab/bitbucket # all users added must have push access to your content repository.
  # repo: owner-name/repo-name # Path to your GitHub repository

# https://decapcms.org/docs/configuration-options/
publish_mode: editorial_workflow
media_folder: "docs/.vuepress/public/media" # Media files will be stored in the repo under docs/.vuepress/public/media
public_folder: "/media" # The src attribute for uploaded media will begin with /media
summary: "{{dirname}}. Last updated at {{commit_date}}"
editor:
  preview: false # disabled markdown preview in CMS
collections:
  - name: "songs" # Used in routes, e.g., /admin/collections/songs
    label: "Songs" # Used in the UI
    label_singular: Song
    folder: "docs/songs" # The path to the folder where the documents are stored
    nested: # adding a nested object will show the collection folder structure
      depth: 2 # max depth to show in the collection tree
    fields: # The fields for each document, usually in front matter
      # https://v2.vuepress.vuejs.org/advanced/cookbook/usage-of-client-config.html#layouts
      - {label: "lastUpdated", name: "lastUpdated", widget: "hidden", default: true}
      - {label: "contributors", name: "contributors", widget: "boolean", default: true}
      - {label: "externalLinkIcon", name: "externalLinkIcon", widget: "boolean", default: false}
      - label: "Entry Date"
        name: "date"
        widget: "datetime"
        format: 'YYYY-MM-DD'
        time_format: false
        required: true
      - {label: "Body", name: "body", widget: "markdown", default: "# Song title (Composer/ Artist)"}
